export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const SHOW_FAVORITE = "SHOW_FAVORITE";
export const HIDE_FAVORITE = "HIDE_FAVORITE";
export const REMOVE_MOVIE_FROM_FAVORITE = "REMOVE_MOVIE_FROM_FAVORITE";
